# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('empresas', '0002_initial'),
        ('tramites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('placa', models.CharField(help_text='Placa del vehículo (ej: ABC-123)', max_length=10, unique=True, validators=[utils.validators.validar_placa_vehicular], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio_fabricacion', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('numero_serie', models.CharField(blank=True, max_length=50, verbose_name='Número de Serie/Chasis')),
                ('numero_motor', models.CharField(blank=True, max_length=50, verbose_name='Número de Motor')),
                ('capacidad_sentados', models.PositiveIntegerField(verbose_name='Capacidad de Pasajeros Sentados')),
                ('tipo_vehiculo', models.CharField(choices=[('AUTO', 'Auto'), ('MINIVAN', 'Minivan'), ('VAN', 'Van'), ('MICROBUS', 'Microbús'), ('OMNIBUS', 'Ómnibus')], max_length=20, verbose_name='Tipo de Vehículo')),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('HABILITADO', 'Habilitado'), ('BAJA', 'Baja'), ('NO_HABILITADO', 'No Habilitado')], default='PROPUESTO', max_length=20, verbose_name='Estado')),
                ('numero_tiv', models.CharField(blank=True, help_text='Tarjeta de Identificación Vehicular', max_length=50, verbose_name='Número TIV')),
                ('fecha_venc_soat', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento SOAT')),
                ('fecha_venc_citv', models.DateField(blank=True, help_text='Certificado de Inspección Técnica Vehicular', null=True, verbose_name='Fecha Vencimiento CITV')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('autorizacion_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_principales', to='autorizaciones.autorizacion', verbose_name='Autorización Principal')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa_propietaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='empresas.empresatransporte', verbose_name='Empresa Propietaria')),
                ('vehiculo_sustituido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_sustitutos', to='vehiculos.vehiculo', verbose_name='Vehículo Sustituido')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='HabilitacionVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_habilitacion', models.CharField(blank=True, max_length=50, verbose_name='Número de Habilitación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('BAJA', 'Baja'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, help_text='Motivo de la habilitación o cambio de estado', verbose_name='Motivo')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_vehiculares', to='autorizaciones.autorizacion', verbose_name='Autorización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tramite_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitaciones_vehiculares', to='tramites.tramite', verbose_name='Trámite de Origen')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Habilitación Vehicular',
                'verbose_name_plural': 'Habilitaciones Vehiculares',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
