# Generated by Django 5.2.9 on 2025-12-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_add_tiposervicio_tipovehiculo'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitacionvehicular',
            name='fecha_autorizacion_transportista',
            field=models.DateField(blank=True, help_text='Fecha de inicio de autorización como transportista', null=True, verbose_name='Fecha Autorización Transportista'),
        ),
        migrations.AddField(
            model_name='habilitacionvehicular',
            name='fecha_expedicion_tuc',
            field=models.DateField(blank=True, help_text='Fecha en que se expidió la TUC', null=True, verbose_name='Fecha Expedición TUC'),
        ),
        migrations.AddField(
            model_name='habilitacionvehicular',
            name='fecha_expiracion_transportista',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de autorización como transportista', null=True, verbose_name='Fecha Expiración Transportista'),
        ),
        migrations.AddField(
            model_name='habilitacionvehicular',
            name='numero_tuc',
            field=models.CharField(blank=True, help_text='Tarjeta Única de Circulación', max_length=50, verbose_name='Número TUC'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='configuracion.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
