# Generated by Django 5.2.9 on 2025-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_tipo_vehiculo_fk_and_tuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso bruto vehicular en kilogramos', max_digits=10, null=True, verbose_name='Peso Bruto (kg)'),
        ),
    ]
