# Generated by Django 5.2.9 on 2025-12-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_categoriavehiculo_tipovehiculo_categoria'),
        ('vehiculos', '0003_vehiculo_peso_bruto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carroceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='configuracion.tipovehiculo', verbose_name='Carrocería'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='configuracion.categoriavehiculo', verbose_name='Categoría'),
        ),
    ]
