# Generated by Django 5.2.9 on 2025-12-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_remove_tipovehiculo_categoria_and_more'),
        ('vehiculos', '0004_remove_vehiculo_tipo_vehiculo_vehiculo_carroceria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='carroceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='configuracion.carroceria', verbose_name='Carrocería'),
        ),
    ]
