# Generated by Django 5.2.11 on 2026-03-09 14:49

import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorizaciones", "0005_autorizacion_archivo_resolucion"),
        ("configuracion", "0008_alter_ruta_ambito"),
        ("empresas", "0002_initial"),
        ("vehiculos", "0006_vehiculo_archivo_resolucion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="placa",
            field=models.CharField(
                help_text="Placa del vehículo (ej: ABC-123)",
                max_length=10,
                validators=[utils.validators.validar_placa_vehicular],
                verbose_name="Placa",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiculo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "BAJA"), _negated=True),
                fields=("placa",),
                name="uq_placa_unica_si_no_esta_baja",
            ),
        ),
    ]
