# Generated by Django 5.2.11 on 2026-03-12 15:17

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculos", "0007_alter_vehiculo_placa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="anio_fabricacion",
            field=models.PositiveIntegerField(
                validators=[utils.validators.validar_anio_fabricacion_vehiculo],
                verbose_name="Año de Fabricación",
            ),
        ),
    ]
