# Generated by Django 5.2.9 on 2025-12-12 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tramite_cambio_estado', models.BooleanField(default=True, verbose_name='Email en cambio de estado de trámite')),
                ('email_tramite_observado', models.BooleanField(default=True, verbose_name='Email cuando trámite es observado')),
                ('email_tramite_aprobado', models.BooleanField(default=True, verbose_name='Email cuando trámite es aprobado/denegado')),
                ('email_vencimientos', models.BooleanField(default=True, verbose_name='Email de alertas de vencimiento')),
                ('email_plazo_subsanacion', models.BooleanField(default=True, verbose_name='Email de plazo de subsanación')),
                ('app_tramite_cambio_estado', models.BooleanField(default=True, verbose_name='Notificación in-app en cambio de estado')),
                ('app_vencimientos', models.BooleanField(default=True, verbose_name='Notificación in-app de vencimientos')),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=30, help_text='Número de días antes del vencimiento para enviar alerta', verbose_name='Días de anticipación para alertas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialEmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254, verbose_name='Email destino')),
                ('nombre_destino', models.CharField(blank=True, max_length=200, verbose_name='Nombre destino')),
                ('tipo', models.CharField(choices=[('tramite_recibido', 'Trámite Recibido'), ('tramite_evaluacion', 'Trámite en Evaluación Técnica'), ('tramite_observado', 'Trámite Observado'), ('tramite_subsanado', 'Trámite Subsanado'), ('tramite_legal', 'Trámite en Revisión Legal'), ('tramite_firma', 'Trámite Pendiente de Firma'), ('tramite_aprobado', 'Trámite Aprobado'), ('tramite_denegado', 'Trámite Denegado'), ('venc_autorizacion', 'Vencimiento de Autorización'), ('venc_soat', 'Vencimiento de SOAT'), ('venc_citv', 'Vencimiento de CITV'), ('venc_licencia', 'Vencimiento de Licencia'), ('venc_habilitacion', 'Vencimiento de Habilitación'), ('plazo_subsanacion', 'Plazo de Subsanación Próximo a Vencer'), ('sistema', 'Notificación del Sistema')], default='sistema', max_length=30, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('tramite_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Trámite')),
                ('empresa_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Empresa')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('post_office_email_id', models.IntegerField(blank=True, null=True, verbose_name='ID en Post Office')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Email Enviado',
                'verbose_name_plural': 'Historial de Emails Enviados',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['email_destino'], name='notificacio_email_d_afe0c9_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_dc5e60_idx'), models.Index(fields=['enviado'], name='notificacio_enviado_5a355b_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_f6d78f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tramite_recibido', 'Trámite Recibido'), ('tramite_evaluacion', 'Trámite en Evaluación Técnica'), ('tramite_observado', 'Trámite Observado'), ('tramite_subsanado', 'Trámite Subsanado'), ('tramite_legal', 'Trámite en Revisión Legal'), ('tramite_firma', 'Trámite Pendiente de Firma'), ('tramite_aprobado', 'Trámite Aprobado'), ('tramite_denegado', 'Trámite Denegado'), ('venc_autorizacion', 'Vencimiento de Autorización'), ('venc_soat', 'Vencimiento de SOAT'), ('venc_citv', 'Vencimiento de CITV'), ('venc_licencia', 'Vencimiento de Licencia'), ('venc_habilitacion', 'Vencimiento de Habilitación'), ('plazo_subsanacion', 'Plazo de Subsanación Próximo a Vencer'), ('sistema', 'Notificación del Sistema')], default='sistema', max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('url', models.CharField(blank=True, help_text='URL para redirigir al hacer clic en la notificación', max_length=500, verbose_name='URL de acción')),
                ('tramite_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Trámite')),
                ('empresa_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Empresa')),
                ('vehiculo_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Vehículo')),
                ('conductor_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Conductor')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_2df5d5_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_83839e_idx')],
            },
        ),
    ]
