# Generated by Django 5.2.9 on 2025-12-10 07:30

import apps.documentos.models
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0001_initial'),
        ('tramites', '__first__'),
        ('vehiculos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('INFORME_TECNICO', 'Informe Técnico'), ('PROYECTO_RESOLUCION', 'Proyecto de Resolución'), ('RESOLUCION', 'Resolución'), ('TIV', 'Tarjeta de Identificación Vehicular'), ('SOAT', 'SOAT'), ('CITV', 'CITV'), ('LICENCIA', 'Licencia de Conducir'), ('DNI', 'DNI'), ('CONTRATO', 'Contrato'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to=apps.documentos.models.documento_upload_path, validators=[utils.validators.validar_solo_pdf, utils.validators.ValidarTamanioArchivo(10)], verbose_name='Archivo PDF')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el documento ha sido verificado', verbose_name='Verificado')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='conductores.conductor', verbose_name='Conductor Asociado')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tramites.tramite', verbose_name='Trámite')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='vehiculos.vehiculo', verbose_name='Vehículo Asociado')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
