# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.utils.timezone
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado_anterior', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado Nuevo')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('accion', models.CharField(blank=True, max_length=100, verbose_name='Acción Realizada')),
            ],
            options={
                'verbose_name': 'Historial de Trámite',
                'verbose_name_plural': 'Historial de Trámites',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_expediente', models.CharField(help_text='Formato: EXP-YYYY-NNNNN', max_length=20, unique=True, verbose_name='Número de Expediente')),
                ('tipo_tramite', models.CharField(choices=[('AUTORIZACION_INICIAL', 'Autorización Inicial'), ('MODIFICACION_AUTORIZACION', 'Modificación de Autorización'), ('INCREMENTO_FLOTA', 'Incremento de Flota'), ('SUSTITUCION_VEHICULO', 'Sustitución de Vehículo'), ('BAJA_VEHICULO', 'Baja de Vehículo'), ('HABILITACION_CONDUCTOR', 'Habilitación de Conductor'), ('BAJA_CONDUCTOR', 'Baja de Conductor')], max_length=30, verbose_name='Tipo de Trámite')),
                ('estado', django_fsm.FSMField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=50, protected=True, verbose_name='Estado')),
                ('descripcion_solicitud', models.TextField(verbose_name='Descripción de la Solicitud')),
                ('fecha_presentacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Presentación')),
                ('plazo_subsanacion', models.DateField(blank=True, null=True, verbose_name='Plazo de Subsanación')),
                ('observaciones_tecnicas', models.TextField(blank=True, verbose_name='Observaciones Técnicas')),
                ('observaciones_legales', models.TextField(blank=True, verbose_name='Observaciones Legales')),
                ('numero_resolucion', models.CharField(blank=True, help_text='Número de la resolución que resuelve el trámite', max_length=50, verbose_name='Número de Resolución')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
