# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('conductores', '0001_initial'),
        ('empresas', '0002_initial'),
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtramite',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='autorizaciones.autorizacion', verbose_name='Autorización Relacionada'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Para trámites de habilitación/baja de conductores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='conductores.conductor', verbose_name='Conductor Relacionado'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='empresas.empresatransporte', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='usuario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
    ]
