# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0002_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Para trámites de incremento/sustitución/baja de vehículos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='vehiculos.vehiculo', verbose_name='Vehículo Relacionado'),
        ),
        migrations.AddField(
            model_name='historialtramite',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tramites.tramite', verbose_name='Trámite'),
        ),
    ]
