# Generated by Django 5.2.9 on 2025-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='numero_expediente',
            field=models.CharField(blank=True, help_text='Formato: EXP-YYYY-NNNNN', max_length=20, unique=True, verbose_name='Número de Expediente'),
        ),
    ]
