# Generated by Django 5.2.9 on 2025-12-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_numero_expediente_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_json', models.JSONField(default=dict, help_text='Datos específicos según el tipo de trámite', verbose_name='Datos del Trámite')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='tramites.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Datos de Trámite',
                'verbose_name_plural': 'Datos de Trámites',
            },
        ),
    ]
