# Generated by Django 5.2.9 on 2025-12-11 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_conductor_empresa'),
        ('tramites', '0005_datos_tramite'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='expediente_externo',
            field=models.CharField(blank=True, help_text='Número de expediente para hojas de ruta (ingresado por el usuario)', max_length=50, verbose_name='N° Expediente Hoja de Ruta'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='numero_expediente',
            field=models.CharField(blank=True, help_text='Formato: EXP-YYYY-NNNNN (generado automáticamente)', max_length=20, unique=True, verbose_name='Número de Expediente'),
        ),
        migrations.CreateModel(
            name='ConductorTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('nombres', models.CharField(blank=True, max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('licencia_numero', models.CharField(blank=True, max_length=20, verbose_name='N° Licencia')),
                ('licencia_categoria', models.CharField(blank=True, max_length=10, verbose_name='Categoría Licencia')),
                ('licencia_fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión Licencia')),
                ('licencia_fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Venc. Licencia')),
                ('estado_proceso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proceso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('conductor_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramite_origen', to='conductores.conductor', verbose_name='Conductor Creado')),
                ('conductor_existente', models.ForeignKey(blank=True, help_text='Para baja de conductor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_conductor', to='conductores.conductor', verbose_name='Conductor Existente')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores_tramite', to='tramites.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Conductor en Trámite',
                'verbose_name_plural': 'Conductores en Trámite',
                'ordering': ['fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteHojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente_externo', models.CharField(help_text='Número de expediente para hojas de ruta', max_length=50, verbose_name='Nro. Expediente Hoja de Ruta')),
                ('estado_tramite', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado del Trámite al Registrar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_hoja_ruta', to='tramites.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Expediente Hoja de Ruta',
                'verbose_name_plural': 'Expedientes Hoja de Ruta',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, verbose_name='N° Serie')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='N° Documento')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('descripcion_tarifa', models.CharField(max_length=255, verbose_name='Descripción/Tarifa')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_pago', to='tramites.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_nueva', models.CharField(blank=True, max_length=10, verbose_name='Placa Nueva')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('anio_fabricacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('numero_serie', models.CharField(blank=True, max_length=50, verbose_name='Número de Serie/Chasis')),
                ('numero_motor', models.CharField(blank=True, max_length=50, verbose_name='Número de Motor')),
                ('capacidad_pasajeros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad de Pasajeros')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Vehículo')),
                ('numero_tarjeta_propiedad', models.CharField(blank=True, max_length=50, verbose_name='N° Tarjeta de Propiedad')),
                ('fecha_venc_soat', models.DateField(blank=True, null=True, verbose_name='Fecha Venc. SOAT')),
                ('fecha_venc_citv', models.DateField(blank=True, null=True, verbose_name='Fecha Venc. CITV')),
                ('estado_proceso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Proceso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_tramite', to='tramites.tramite', verbose_name='Trámite')),
                ('vehiculo_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramite_origen', to='vehiculos.vehiculo', verbose_name='Vehículo Creado')),
                ('vehiculo_existente', models.ForeignKey(blank=True, help_text='Para sustitución o baja de vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_vehiculo', to='vehiculos.vehiculo', verbose_name='Vehículo Existente')),
            ],
            options={
                'verbose_name': 'Vehículo en Trámite',
                'verbose_name_plural': 'Vehículos en Trámite',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
