# Generated by Django 5.2.9 on 2025-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_agregar_modelos_expediente_pago_vehiculos_conductores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='solicitante_dni',
            field=models.CharField(blank=True, help_text='DNI de la persona que presenta el trámite', max_length=15, verbose_name='DNI del Solicitante'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='solicitante_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Solicitante'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='solicitante_nombres',
            field=models.CharField(blank=True, help_text='Nombres completos del solicitante', max_length=200, verbose_name='Nombres del Solicitante'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='solicitante_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Solicitante'),
        ),
    ]
