# Generated by Django 5.2.9 on 2025-12-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_add_solicitante_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculotramite',
            name='fecha_autorizacion_transportista',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Autorización Transportista'),
        ),
        migrations.AddField(
            model_name='vehiculotramite',
            name='fecha_expedicion_tuc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Expedición TUC'),
        ),
        migrations.AddField(
            model_name='vehiculotramite',
            name='fecha_expiracion_transportista',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Expiración Transportista'),
        ),
        migrations.AddField(
            model_name='vehiculotramite',
            name='numero_tuc',
            field=models.CharField(blank=True, help_text='Tarjeta Única de Circulación', max_length=50, verbose_name='Número TUC'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(choices=[('AUTORIZACION_INICIAL', 'Autorización Inicial'), ('MODIFICACION_AUTORIZACION', 'Modificación de Autorización'), ('RENOVACION_AUTORIZACION', 'Renovación de Autorización'), ('BAJA_AUTORIZACION', 'Baja de Autorización (Voluntaria)'), ('CANCELACION_AUTORIZACION', 'Cancelación de Autorización (Sanción)'), ('INCREMENTO_FLOTA', 'Incremento de Flota'), ('SUSTITUCION_VEHICULO', 'Sustitución de Vehículo'), ('BAJA_VEHICULO', 'Baja de Vehículo'), ('HABILITACION_CONDUCTOR', 'Habilitación de Conductor'), ('BAJA_CONDUCTOR', 'Baja de Conductor')], max_length=30, verbose_name='Tipo de Trámite'),
        ),
    ]
