# Generated by Django 5.2.9 on 2025-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_vehiculotramite_tuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(choices=[('AUTORIZACION_INICIAL', 'Autorización Inicial'), ('MODIFICACION_AUTORIZACION', 'Modificación de Autorización'), ('RENOVACION_AUTORIZACION', 'Renovación de Autorización'), ('BAJA_AUTORIZACION', 'Baja de Autorización (Voluntaria)'), ('SUSPENSION_AUTORIZACION', 'Suspensión de Autorización (Sanción)'), ('INCREMENTO_FLOTA', 'Incremento de Flota'), ('SUSTITUCION_VEHICULO', 'Sustitución de Vehículo'), ('BAJA_VEHICULO', 'Baja de Vehículo'), ('HABILITACION_CONDUCTOR', 'Habilitación de Conductor'), ('BAJA_CONDUCTOR', 'Baja de Conductor')], max_length=30, verbose_name='Tipo de Trámite'),
        ),
    ]
