# Generated by Django 5.2.9 on 2025-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0009_alter_tramite_tipo_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculotramite',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo'),
        ),
    ]
