# Generated by Django 5.2.9 on 2025-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0010_alter_vehiculotramite_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculotramite',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Bruto (kg)'),
        ),
    ]
