# Generated by Django 5.2.9 on 2025-12-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_remove_tipovehiculo_categoria_and_more'),
        ('tramites', '0012_remove_vehiculotramite_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculotramite',
            name='carroceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.carroceria', verbose_name='Carrocería'),
        ),
    ]
