# Generated by Django 5.2.9 on 2026-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0013_alter_vehiculotramite_carroceria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='archivo_resolucion',
            field=models.FileField(blank=True, help_text='Documento PDF de la resolución', null=True, upload_to='resoluciones/tramites/', verbose_name='Archivo de Resolución'),
        ),
    ]
