# Generated by Django 5.2.12 on 2026-03-25 14:46

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0014_tramite_archivo_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductortramite',
            name='dni',
            field=models.CharField(blank=True, max_length=15, validators=[utils.validators.validar_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='solicitante_dni',
            field=models.CharField(blank=True, help_text='DNI de la persona que presenta el trámite', max_length=15, validators=[utils.validators.validar_dni], verbose_name='DNI del Solicitante'),
        ),
    ]
