# Generated by Django 5.2.11 on 2026-06-15 18:08

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0015_alter_conductortramite_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientehojaruta',
            name='estado_tramite',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('EN_DIRECCION_ADMINISTRATIVA', 'En Dirección Administrativa'), ('EN_DIRECCION_GENERAL', 'En Dirección General'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado del Trámite al Registrar'),
        ),
        migrations.AlterField(
            model_name='historialtramite',
            name='estado_anterior',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('EN_DIRECCION_ADMINISTRATIVA', 'En Dirección Administrativa'), ('EN_DIRECCION_GENERAL', 'En Dirección General'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialtramite',
            name='estado_nuevo',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('EN_DIRECCION_ADMINISTRATIVA', 'En Dirección Administrativa'), ('EN_DIRECCION_GENERAL', 'En Dirección General'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], max_length=30, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=django_fsm.FSMField(choices=[('RECIBIDO', 'Recibido'), ('EN_EVAL_TECNICA', 'En Evaluación Técnica'), ('EN_DIRECCION_ADMINISTRATIVA', 'En Dirección Administrativa'), ('EN_DIRECCION_GENERAL', 'En Dirección General'), ('OBSERVADO', 'Observado'), ('EN_REVISION_LEGAL', 'En Revisión Legal'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=50, protected=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(choices=[('AUTORIZACION_INICIAL', 'Autorización Inicial'), ('MODIFICACION_AUTORIZACION', 'Actualización de Empresa y Autorización'), ('RENOVACION_AUTORIZACION', 'Renovación de Autorización'), ('RENOVACION_TUC', 'Renovación de TUC'), ('BAJA_AUTORIZACION', 'Baja de Autorización (Voluntaria)'), ('SUSPENSION_AUTORIZACION', 'Suspensión de Autorización (Sanción)'), ('INCREMENTO_FLOTA', 'Incremento de Flota'), ('SUSTITUCION_VEHICULO', 'Sustitución de Vehículo'), ('BAJA_VEHICULO', 'Baja de Vehículo'), ('HABILITACION_CONDUCTOR', 'Habilitación de Conductor'), ('BAJA_CONDUCTOR', 'Baja de Conductor')], max_length=30, verbose_name='Tipo de Trámite'),
        ),
    ]
