# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador (ej: SUTRAN, PNP)', max_length=100)),
                ('clave', models.CharField(editable=False, help_text='Clave de API generada automáticamente', max_length=64, unique=True)),
                ('entidad', models.CharField(help_text='Entidad a la que pertenece la clave', max_length=200)),
                ('email_contacto', models.EmailField(blank=True, help_text='Email de contacto de la entidad', max_length=254)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la clave está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Fecha de expiración (dejar vacío para no expirar)', null=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, help_text='Última vez que se usó la clave', null=True)),
                ('total_consultas', models.PositiveIntegerField(default=0, help_text='Total de consultas realizadas')),
                ('limite_diario', models.PositiveIntegerField(default=1000, help_text='Límite de consultas por día (0 = sin límite)')),
                ('consultas_hoy', models.PositiveIntegerField(default=0, help_text='Consultas realizadas hoy')),
                ('fecha_reset_diario', models.DateField(blank=True, help_text='Fecha del último reset del contador diario', null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_consultada', models.CharField(max_length=10)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('resultado_exitoso', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(default=0, help_text='Tiempo de respuesta en milisegundos')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='consultas.apikey')),
            ],
            options={
                'verbose_name': 'Registro de Consulta',
                'verbose_name_plural': 'Registros de Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
