# Generated by Django 5.2.9 on 2025-12-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código único identificador (ej: F001, DIARIO-AM)', max_length=20, unique=True, verbose_name='Código de Frecuencia')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la frecuencia', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la frecuencia', verbose_name='Descripción')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True, verbose_name='Hora de Llegada Estimada')),
                ('dias_operacion', models.CharField(default='LU,MA,MI,JU,VI,SA,DO', help_text='Días de la semana separados por coma (ej: LU,MA,MI,JU,VI)', max_length=50, verbose_name='Días de Operación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la frecuencia está disponible para asignación', verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
                'ordering': ['hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código único identificador de la ruta (ej: R001, MDD-PEM-001)', max_length=20, unique=True, verbose_name='Código de Ruta')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ruta', max_length=200, verbose_name='Nombre de Ruta')),
                ('origen', models.CharField(help_text='Ciudad/localidad de origen', max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(help_text='Ciudad/localidad de destino', max_length=100, verbose_name='Destino')),
                ('puntos_intermedios', models.TextField(blank=True, help_text='Puntos intermedios de la ruta, separados por coma', verbose_name='Puntos Intermedios')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia aproximada en kilómetros', max_digits=8, null=True, verbose_name='Distancia (km)')),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(blank=True, help_text='Tiempo estimado de viaje en minutos', null=True, verbose_name='Tiempo Estimado (minutos)')),
                ('ambito', models.CharField(default='Regional Madre de Dios', help_text='Ámbito territorial de la ruta', max_length=100, verbose_name='Ámbito')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la ruta está disponible para asignación', verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['codigo'],
            },
        ),
    ]
