# Generated by Django 5.2.9 on 2025-12-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_categoriavehiculo_tipovehiculo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='categoriavehiculo',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima'),
        ),
        migrations.AddField(
            model_name='categoriavehiculo',
            name='capacidad_minima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Mínima'),
        ),
        migrations.AddField(
            model_name='categoriavehiculo',
            name='peso_bruto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Bruto Máximo (kg)'),
        ),
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código único de la carrocería (ej: SEDAN, OMNIBUS)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la carrocería', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('capacidad_minima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Mínima')),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrocerias', to='configuracion.categoriavehiculo', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Carrocería',
                'verbose_name_plural': 'Carrocerías',
                'ordering': ['nombre'],
            },
        ),
    ]
