# Generated by Django 5.2.9 on 2025-12-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_remove_tipovehiculo_categoria_and_more'),
        ('tramites', '0013_alter_vehiculotramite_carroceria'),
        ('vehiculos', '0005_alter_vehiculo_carroceria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoVehiculo',
        ),
    ]
