# Generated by Django 5.2.9 on 2026-01-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_delete_tipovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='ambito',
            field=models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANCASH', 'Áncash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAVELICA', 'Huancavelica'), ('HUANUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('MOQUEGUA', 'Moquegua'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], default='MADRE_DE_DIOS', help_text='Ámbito territorial de la ruta', max_length=100, verbose_name='Ámbito'),
        ),
    ]
