# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('empresas', '__first__'),
        ('tramites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[utils.validators.validar_dni], verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('licencia_numero', models.CharField(max_length=20, verbose_name='Número de Licencia')),
                ('licencia_categoria', models.CharField(choices=[('AI', 'A-I'), ('AII-A', 'A-II-A'), ('AII-B', 'A-II-B'), ('AIII-A', 'A-III-A'), ('AIII-B', 'A-III-B'), ('AIII-C', 'A-III-C')], max_length=10, verbose_name='Categoría de Licencia')),
                ('licencia_fecha_emision', models.DateField(verbose_name='Fecha de Emisión de Licencia')),
                ('licencia_fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento de Licencia')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HabilitacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_habilitacion', models.CharField(blank=True, max_length=50, verbose_name='Número de Habilitación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('BAJA', 'Baja'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, help_text='Motivo de la habilitación o cambio de estado', verbose_name='Motivo')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_conductores', to='autorizaciones.autorizacion', verbose_name='Autorización')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones', to='conductores.conductor', verbose_name='Conductor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_conductores', to='empresas.empresatransporte', verbose_name='Empresa')),
                ('tramite_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitaciones_conductores', to='tramites.tramite', verbose_name='Trámite de Origen')),
            ],
            options={
                'verbose_name': 'Habilitación de Conductor',
                'verbose_name_plural': 'Habilitaciones de Conductores',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
