# Generated by Django 5.2.9 on 2025-12-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa de transporte a la que pertenece el conductor', on_delete=django.db.models.deletion.PROTECT, related_name='conductores', to='empresas.empresatransporte', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
