# Generated by Django 5.2.9 on 2026-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_conductor_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='archivo_resolucion',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/conductores/', verbose_name='Archivo de Resolución'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_resolucion',
            field=models.CharField(blank=True, help_text='Resolución de habilitación', max_length=50, verbose_name='Número de Resolución'),
        ),
    ]
