# Generated by Django 5.2.11 on 2026-03-12 15:17

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conductores", "0003_conductor_archivo_resolucion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductor",
            name="fecha_nacimiento",
            field=models.DateField(
                validators=[utils.validators.validar_anio_nacimiento_conductor],
                verbose_name="Fecha de Nacimiento",
            ),
        ),
    ]
