# Generated by Django 5.2.9 on 2025-12-10 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_resolucion', models.CharField(max_length=50, unique=True, verbose_name='Número de Resolución')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha de Resolución')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin de Vigencia')),
                ('ambito', models.CharField(default='Regional Madre de Dios', help_text='Ámbito territorial de la autorización', max_length=100, verbose_name='Ámbito')),
                ('tipo_servicio', models.CharField(choices=[('REGULAR', 'Regular'), ('ESPECIAL', 'Especial'), ('TURISTICO', 'Turístico')], default='REGULAR', max_length=20, verbose_name='Tipo de Servicio')),
                ('modalidad', models.CharField(blank=True, help_text='Modalidad del servicio (ej: Transporte regular de personas)', max_length=100, verbose_name='Modalidad')),
                ('descripcion_rutas', models.TextField(help_text='Detalle de las rutas autorizadas', verbose_name='Descripción de Rutas')),
                ('frecuencias', models.TextField(blank=True, help_text='Frecuencias y horarios autorizados', verbose_name='Frecuencias')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='empresas.empresatransporte', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
                'ordering': ['-fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, verbose_name='Valor Nuevo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='autorizaciones.autorizacion', verbose_name='Autorización')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Autorización',
                'verbose_name_plural': 'Historial de Autorizaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
