# Generated by Django 5.2.9 on 2025-12-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='frecuencias_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Frecuencias de servicio asignadas', related_name='autorizaciones', to='configuracion.frecuencia', verbose_name='Frecuencias Asignadas'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='rutas',
            field=models.ManyToManyField(blank=True, help_text='Rutas asignadas a esta autorización', related_name='autorizaciones', to='configuracion.ruta', verbose_name='Rutas Autorizadas'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='descripcion_rutas',
            field=models.TextField(blank=True, help_text='Detalle adicional de las rutas autorizadas', verbose_name='Descripción de Rutas'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='frecuencias',
            field=models.TextField(blank=True, help_text='Descripción adicional de frecuencias y horarios', verbose_name='Frecuencias (texto)'),
        ),
    ]
