# Generated by Django 5.2.9 on 2025-12-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0003_cambiar_ambito_a_choices'),
        ('configuracion', '0002_add_tiposervicio_tipovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacion',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='configuracion.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
