# Generated by Django 5.2.9 on 2026-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0004_tipo_servicio_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='archivo_resolucion',
            field=models.FileField(blank=True, help_text='Documento PDF de la resolución', null=True, upload_to='resoluciones/autorizaciones/', verbose_name='Archivo de Resolución'),
        ),
    ]
