# Generated by Django 5.2.9 on 2025-12-10 07:30

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyentes (11 dígitos)', max_length=11, unique=True, validators=[utils.validators.validar_ruc], verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('domicilio_fiscal', models.TextField(verbose_name='Domicilio Fiscal')),
                ('departamento', models.CharField(default='Madre de Dios', max_length=50, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('representante_legal', models.CharField(max_length=255, verbose_name='Representante Legal')),
                ('dni_representante', models.CharField(max_length=8, validators=[utils.validators.validar_dni], verbose_name='DNI del Representante')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Empresa de Transporte',
                'verbose_name_plural': 'Empresas de Transporte',
                'ordering': ['razon_social'],
            },
        ),
    ]
