# Generated by Django 5.2.9 on 2025-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN_SISTEMA', 'Administrador del Sistema'), ('MESA_PARTES', 'Mesa de Partes'), ('ESPECIALISTA_TECNICO', 'Especialista Técnico'), ('ASESORIA_LEGAL', 'Asesoría Legal'), ('DIRECTOR', 'Director'), ('CONSULTA_INTERNA', 'Consulta Interna'), ('CONSULTA_INSPECTOR', 'Consulta Inspector')], default='CONSULTA_INTERNA', help_text='Rol del usuario en el sistema', max_length=30, verbose_name='Rol'),
        ),
    ]
